import os

CLICKTAIL_CLICKHOUSE_HOST = os.environ["CLICKTAIL_CLICKHOUSE_HOST"]
CLICKTAIL_CLICKHOUSE_DATABASE = os.environ["CLICKTAIL_CLICKHOUSE_DATABASE"]
CLICKTAIL_CLICKHOUSE_TABLE = os.environ["CLICKTAIL_CLICKHOUSE_TABLE"]
CLICKTAIL_CLICKHOUSE_USERNAME = os.environ["CLICKTAIL_CLICKHOUSE_USERNAME"]
CLICKTAIL_CLICKHOUSE_PASSWORD = os.environ["CLICKTAIL_CLICKHOUSE_PASSWORD"]
CLICKTAIL_CLICKHOUSE_PAYLOAD_COLUMN = os.environ["CLICKTAIL_CLICKHOUSE_PAYLOAD_COLUMN"]
