import os

CLICKTAIL_CLICKHOUSE_HOST: str = os.environ["CLICKTAIL_CLICKHOUSE_HOST"]
CLICKTAIL_CLICKHOUSE_DATABASE: str = os.environ["CLICKTAIL_CLICKHOUSE_DATABASE"]
CLICKTAIL_CLICKHOUSE_TABLE: str = os.environ["CLICKTAIL_CLICKHOUSE_TABLE"]
CLICKTAIL_CLICKHOUSE_USERNAME: str = os.environ["CLICKTAIL_CLICKHOUSE_USERNAME"]
CLICKTAIL_CLICKHOUSE_PASSWORD: str = os.environ["CLICKTAIL_CLICKHOUSE_PASSWORD"]
CLICKTAIL_CLICKHOUSE_PAYLOAD_COLUMN: str = os.environ[
    "CLICKTAIL_CLICKHOUSE_PAYLOAD_COLUMN"
]
